config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :restaurants
  #Landing page
  root 'landing#index'

  # Crud routes for reviews and restaurants
  resources :reviews
  resources :restaurants
  resorces :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
end

app/models/review.rb
class Review < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
    before_action :set_restaurant, only: [:show, :edit, :update, :destroy]
  # before_action :admin? , only: [:new, :edit, :create, :update, :destroy]
  # before_action :authenticate_user!, only: [:index, :new, :create, :show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    redirect_to @restaurant
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    if @restaurant.update(restaurant_params)
      flash[:success] = ""+:restaurant_name.to_s + " is updated!"
      redirect_to @restaurant
      # Handle a successful update.
    else
      render 'edit'
    end
  end

  private
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    def restaurant_params
      params.require(:restaurant).permit(:restaurant_name, :picture, :address1, :address2,
                                        :postal_code, :contact)
    end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:user_picture, :name, :user_spending, :no_of_parties, :overall_rating, :who_brought_me_here, :char_review)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:user_picture,, :name,, :password,, :top_5_restaurants)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/landing/index.html.erb
<h1>Welcome to Foold!</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project421</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= form_with(model: restaurant, local: true) do |form| %>
  <% if restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :restaurant_name %>
    <%= form.text_field :restaurant_name, id: :restaurant_restaurant_name %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.text_field :picture, id: :restaurant_picture %>
  </div>

  <div class="field">
    <%= form.label :address1 %>
    <%= form.text_field :address1, id: :restaurant_address1 %>
  </div>

  <div class="field">
    <%= form.label :address2 %>
    <%= form.text_field :address2, id: :restaurant_address2 %>
  </div>

  <div class="field">
    <%= form.label :postal_code %>
    <%= form.text_field :postal_code, id: :restaurant_postal_code %>
  </div>

  <div class="field">
    <%= form.label :contact %>
    <%= form.text_field :contact, id: :restaurant_contact %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Restaurants</h1>

<table>
  <thead>
    <tr>
      <th>Restaurant name</th>
      <th>Picture</th>
      <th>Address1</th>
      <th>Address2</th>
      <th>Postal code</th>
      <th>Contact</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.restaurant_name %></td>
        <td><%= image_tag(restaurant.picture) %></td>
        <td><%= restaurant.address1 %></td>
        <td><%= restaurant.address2 %></td>
        <td><%= restaurant.postal_code %></td>
        <td><%= restaurant.contact %></td>
        <td><%= link_to 'Show', restaurant %></td>
        <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
        <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= @restaurant.restaurant_name %>
</p>

<p>
  <%= image_tag(@restaurant.picture) %>
</p>

<p>
  <%= @restaurant.address1 %>
</p>

<p>
  <%= @restaurant.address2 %>
</p>

<p>
  <%= @restaurant.postal_code %>
</p>

<p>
  <%= @restaurant.contact %>
</p>

<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %>

app/views/reviews/_form.html.erb
<%= form_with(model: review, local: true) do |form| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_picture %>
    <%= form.text_field :user_picture, id: :review_user_picture %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :review_name %>
  </div>

  <div class="field">
    <%= form.label :user_spending %>
    <%= form.text_field :user_spending, id: :review_user_spending %>
  </div>

  <div class="field">
    <%= form.label :no_of_parties %>
    <%= form.text_field :no_of_parties, id: :review_no_of_parties %>
  </div>

  <div class="field">
    <%= form.label :overall_rating %>
    <%= form.text_field :overall_rating, id: :review_overall_rating %>
  </div>

  <div class="field">
    <%= form.label :who_brought_me_here %>
    <%= select(:who_brought_me_here, options_for_select([['Daniel Food Diary'], ['Miss Tamchiak'], ['Seth Lui']])), id: :review_who_brought_me_here %>
  </div>

  <div class="field">
    <%= form.label :Other_Comments %>
    <%= form.text_field :char_review, id: :review_char_review %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviews</h1>

<table>
  <thead>
    <tr>
      <th>User picture</th>
      <th>Name</th>
      <th>User spending</th>
      <th>No of parties</th>
      <th>Overall rating</th>
      <th>Who brought me here</th>
      <th>Other comments</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= image_tag(review.user_picture, size:"60") %></td>
        <td><%= review.name %></td>
        <td><%= review.user_spending %></td>
        <td><%= review.no_of_parties %></td>
        <td><%= review.overall_rating %></td>
        <td><%= review.who_brought_me_here %></td>
        <td><%= review.char_review %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= image_tag(@review.user_picture, size:"100") %>
</p>

<p>
  <strong>Name:</strong>
  <%= @review.name %>
</p>

<p>
  <strong>I spent: $</strong><%= @review.user_spending %><strong> on:</strong> <%= @review.no_of_parties %> <strong> pax</strong>

</p>

<p>
  <strong>Overall rating:</strong>
  <%= @review.overall_rating %>
</p>

<p>
  <strong>Who brought me here:</strong>
  <%= @review.who_brought_me_here %>
</p>

<p>
  <%= "\"" + @review.char_review + "\""  %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_picture, %>
    <%= form.text_field :user_picture,, id: :user_user_picture, %>
  </div>

  <div class="field">
    <%= form.label :name, %>
    <%= form.text_field :name,, id: :user_name, %>
  </div>

  <div class="field">
    <%= form.label :password, %>
    <%= form.text_field :password,, id: :user_password, %>
  </div>

  <div class="field">
    <%= form.label :top_5_restaurants %>
    <%= form.text_field :top_5_restaurants, id: :user_top_5_restaurants %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>User picture,</th>
      <th>Name,</th>
      <th>Password,</th>
      <th>Top 5 restaurants</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.user_picture, %></td>
        <td><%= user.name, %></td>
        <td><%= user.password, %></td>
        <td><%= user.top_5_restaurants %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User picture,:</strong>
  <%= @user.user_picture, %>
</p>

<p>
  <strong>Name,:</strong>
  <%= @user.name, %>
</p>

<p>
  <strong>Password,:</strong>
  <%= @user.password, %>
</p>

<p>
  <strong>Top 5 restaurants:</strong>
  <%= @user.top_5_restaurants %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>